on:
  workflow_call:
    inputs:
      name:
        type: string
        description: The name of the workflow to call.
        required: true
      artifact-name:
        type: string
        description: The name of the artifact.
        default: NuGet
      code-sign:
        type: boolean
        description: Whether to code sign the build or not.
        default: false
        required: false
    secrets:
      feedUrl:
        required: false
      apiKey:
        required: true
      codeSignTimestampUrl:
        description: The url to the timestamp server.
        required: false
      codeSignKeyVault:
        description: The name of the Azure KeyVault to use.
        required: false
      codeSignClientId:
        description: The client id to use to access the KeyVault.
        required: false
      codeSignTenantId:
        description: The tenant id to use to access the KeyVault.
        required: false
      codeSignClientSecret:
        description: The client secret to use to access the KeyVault.
        required: false
      codeSignCertificate:
        description: The name of the certificate to use to code sign the build.
        required: false

jobs:
  deploy:
    name: ${{ inputs.name }}
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: Artifacts/

      - name: Sign NuGet Packages
        if: ${{ secrets.codeSignKeyVault }}
        shell: pwsh
        working-directory: ${{ inputs.artifacts-path }}
        run: |
          dotnet tool install --global NuGetKeyVaultSignTool
          $timestampUrl = "${{ secrets.codeSignTimestampUrl }}"
          if ($timestampUrl -eq '') {
            Write-Host 'Using Default DigiCert Timestamp Server'
            $timestampUrl = 'http://timestamp.digicert.com'
          }
          NuGetKeyVaultSignTool sign *.nupkg `
            --file-digest sha256 `
            --timestamp-rfc3161 $timestampUrl `
            --timestamp-digest sha256 `
            --azure-key-vault-url '${{ secrets.codeSignKeyVault }}' `
            --azure-key-vault-client-id '${{ secrets.codeSignClientId }}' `
            --azure-key-vault-tenant-id '${{ secrets.codeSignTenantId }}' `
            --azure-key-vault-client-secret '${{ secrets.codeSignClientSecret }}' `
            --azure-key-vault-certificate '${{ secrets.codeSignCertificate }}'
          NuGetKeyVaultSignTool sign *.snupkg `
            --file-digest sha256 `
            --timestamp-rfc3161 $timestampUrl `
            --timestamp-digest sha256 `
            --azure-key-vault-url '${{ secrets.codeSignKeyVault }}' `
            --azure-key-vault-client-id '${{ secrets.codeSignClientId }}' `
            --azure-key-vault-tenant-id '${{ secrets.codeSignTenantId }}' `
            --azure-key-vault-client-secret '${{ secrets.codeSignClientSecret }}' `
            --azure-key-vault-certificate '${{ secrets.codeSignCertificate }}'

      - name: ${{ inputs.name }}
        uses: dansiegel/publish-nuget@master
        with:
            filename: 'Artifacts/*.nupkg'
            feedUrl: ${{ secrets.feedUrl }}
            apiKey: ${{ secrets.apiKey }}