on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: The tag to use for the release.
        default: ${{ github.event.release.tag_name }}
      feedUrl:
        type: string
        description: The NuGet feed to use for the release.
        default: https://api.nuget.org/v3/index.json
        required: false
    secrets:
      apiKey:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: robinraju/release-downloader@v1.3
        with:
          repository: ${{ github.repository }}
          tag: ${{ inputs.tag }}
          fileName: "*"
          out-file-path: "Artifacts/"
          tarBall: false
          zipBall: false

      - name: Publish to NuGet.org
        uses: dansiegel/publish-nuget@master
        with:
          filename: 'Artifacts/*.nupkg'
          feedUrl: ${{ secrets.feedUrl }}
          apiKey: ${{ secrets.apiKey }}
